---
- name: openstack.redhat-subscription
  src: https://github.com/openstack/ansible-role-redhat-subscription
- name: redhat-cip/ansible-role-beaker
  src: https://github.com/redhat-cip/ansible-role-beaker
