---
- name: restart mariadb
  service:
    name: mariadb
    enabled: true
    state: restarted
  become: true
  notify: restart beakerd

- name: restart httpd
  service:
    name: httpd
    enabled: true
    state: restarted
  become: true

- name: restart labcontroller services
  service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  become: true
  with_items:
    - beaker-proxy
    - beaker-watchdog
    - beaker-provision

- name: restart dnsmasq
  service:
    name: dnsmasq
    enabled: true
    state: restarted
  become: true

- name: restart beakerd
  service:
    name: beakerd
    enabled: true
    state: started
  become: true
