---
- name: Get beaker tasks list
  uri:
    url: https://beaker-project.org/tasks/
    return_content: yes
  register: beaker_tasks

- name: Parse rpms list
  set_fact:
    rpms: "{{ beaker_tasks.content.split('\n')|select('search', '<tr>')|map('regex_replace', '<tr><td class=\"n\"><a href=\"(.*.rpm)\">.*</td></tr>', '\\1')|list }}"

- name: Create ansible tmp dir
  tempfile:
    state: directory
  register: tmp_dir

- name: Fetch Beaker default tasks
  get_url:
    dest: '{{ tmp_dir.path }}'
    url: 'https://beaker-project.org/tasks/{{ item }}'
  with_items: '{{ rpms[1:] }}'

- name: Upload Beaker default tasks
  command: bkr task-add {{ tmp_dir.path}}/{{ item }}
  become: true
  with_items: '{{ rpms[1:] }}'
  ignore_errors: true
