---
- name: Get beaker tasks list
  uri:
    url: https://beaker-project.org/tasks/
    return_content: true
  register: beaker_tasks

- name: Parse rpms list
  set_fact:
    rpms: "{{ beaker_tasks.content.split('\n')|select('search', '<tr>')|map('regex_replace', '<tr><td class=\"n\"><a href=\"(.*.rpm)\">.*</td></tr>', '\\1')|list }}"

- name: Fetch Beaker default tasks
  get_url:
    dest: '/tmp/{{ item }}'
    url: 'https://beaker-project.org/tasks/{{ item }}'
  with_items: '{{ rpms[1:] }}'

- name: Upload Beaker default tasks
  shell: bkr task-add /tmp/{{ item }} 2>&1 > /root/bkr_task_add_{{ item }}.log
  args:
    creates: /root/bkr_task_add_{{ item }}.log
  become: true
  with_items: '{{ rpms[1:] }}'
  ignore_errors: true
