---
- name: Install Beaker-Server yum repository
  yum_repository:
    name: beaker-server
    description: Beaker Server - RedHatEnterpriseLinux$releasever
    baseurl: https://beaker-project.org/yum/server/RedHatEnterpriseLinux$releasever/
    gpgcheck: false
    gpgkey: https://beaker-project.org/gpg/RPM-GPG-KEY-beaker-project
  become: true

- name: Install Beaker-Client yum repository
  yum_repository:
    name: beaker-client
    description: Beaker Client - RedHatEnterpriseLinux$releasever
    baseurl: https://beaker-project.org/yum/client/RedHatEnterpriseLinux$releasever/
    gpgcheck: false
    gpgkey: https://beaker-project.org/gpg/RPM-GPG-KEY-beaker-project
  become: true

- name: Install Beaker-Harness yum repository
  yum_repository:
    name: beaker-harness
    description: Beaker Harness - RedHatEnterpriseLinux$releasever
    baseurl: https://beaker-project.org/yum/harness/RedHatEnterpriseLinux{{ ansible_distribution_major_version }}/
    gpgcheck: false
    gpgkey: https://beaker-project.org/gpg/RPM-GPG-KEY-beaker-project
  become: true
