---
- name: Enable httpd
  service:
    name: httpd
    enabled: true
    state: started
  become: true
- name: Populate service facts
  service_facts:
- name: Enable http service in firewalld
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  when:
    - "'firewalld.service' in ansible_facts.services"
    - "ansible_facts.services['firewalld.service']['state'] == 'running'"
  become: true
  tags: [ firewall ]
