---
- name: RHEL Repositories
  command: >
    subscription-manager repos
    --enable rhel-{{ ansible_distribution_major_version }}-server-rpms
    --enable rhel-{{ ansible_distribution_major_version }}-server-extras-rpms
    --enable rhel-{{ ansible_distribution_major_version }}-server-optional-rpms
  become: true
  tags:
    - packages
    - repos

- name: EPEL Repository
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  become: true
  tags:
    - packages
    - repos

- name: Ansible Modules Required Packages
  package:
    name:
      - libselinux-python
      - python-firewall
  become: true
  tags:
    - packages

- name: Populate service facts
  service_facts:
