# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN yum makecache fast && yum install -y python sudo yum-plugin-ovl bash iproute libselinux-python selinux-policy && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all
