---
lint:
  name: yamllint
platforms:
  - name: el7
    image: centos/systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
