# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN yum makecache fast && yum install -y python sudo yum-plugin-ovl bash iproute libselinux-python selinux-policy firewalld && systemctl enable firewalld && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all

# NOTE(Gonéri) Ninja hack to prevent firewalld from loading extra kernel modules
RUN sed -i 's,<module name="nf_conntrack_tftp"/>,,' /usr/lib/firewalld/services/tftp.xml
