---
lint:
  name: yamllint
platforms:
  - name: $TOX_ENVNAME
    image: centos/systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
provisioner:
  name: ansible
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint
scenario:
  name: with-firewalld
verifier:
  name: testinfra
  lint:
    name: flake8
